### ISSUE TITLE
got an assert error `BaseEvent has a std::chrono timestamp, but the backend thread is using rdtsc timestamp`

### ISSUE THREAD

**Issue by zhangzq** [odygrd/quill#68] opened 2020-11-06 05:08 UTC
Please help. Error message:

quill/detail/BackendWorker.h:396: std::chrono::nanoseconds quill::detail::BackendWorker::_get_real_timestamp(const quill::detail::BaseEvent*) const: Assertion `base_event->using_rdtsc() && "BaseEvent has a std::chrono timestamp, but the backend thread is using rdtsc timestamp"' failed.

**Comment by odygrd** [comment] 2020-11-06 06:33
Please can you give some more information in order to reproduce?
Have you tried to define 
‘#define QUILL_CHRONO_CLOCK’ ?

If you did so you need to define it project wise so backend thread also uses it. Can you try passing it on when you invoke cmake as it says in Tweakme.h ?

**Comment by zhangzq** [comment] 2020-11-06 06:45
I did nothing.

 Should I define QUILL_CHRONO_CLOCK? It's not documented.

**Comment by zhangzq** [comment] 2020-11-06 06:49
I looked into the source code. It seems that there missing an `== false` in line 396 of BackendWorker.h:

```C++
 assert(base_event->using_rdtsc() &&
```

should be 

```C++
 assert(base_event->using_rdtsc() == false &&
```

**Comment by odygrd** [comment] 2020-11-06 09:44
`using_rdtsc` Should be true.

Please check if you are defining QUILL_CHRONO_CLOCK somewhere or try to give some more information

**Comment by zhangzq** [comment] 2020-11-09 01:11
It's weired. I greped the whole code space and not found QUILL_CHRONO_CLOCK .

I even never heard of this macro before I encountered this problem.

**Comment by zhangzq** [comment] 2020-11-09 01:12
And the problem is fixed when I add `== false`, which is abnormal in any case.

**Comment by zhangzq** [comment] 2020-11-09 01:20
Here is my guess:

The library libquill.a is compiled with -DNDEBUG (defaultly, I guess). And my program compiled with `-g -O0` without `-DNDEBUG`. There may be a link inconsistent?

**Comment by odygrd** [comment] 2020-11-11 21:43
I could not reproduce. I removed the assertion and I am now using a static_assert.
Could you please try with the latest commit from master and let me know if the problem persists ?

**Comment by odygrd** [comment] 2020-11-15 22:31
Closing this.. please reopen if you have issues again

**Closed by odygrd** 2020-11-15 22:31 UTC
